SOURCES := covid19_splitloop.c COV_rand.c prop_distribution.c distance.c locale.c

OBJECTS := $(SOURCES:%.c=%.o)

PROGRAM = covid19

CC := icc
LD := $(CC)

OMP = -qopenmp
# Use this for Abisko
#OPT = -O3 -mavx
# And this for everything else
OPT = -O3 -xHost
#DEBUG = -O0 -g
CPPFLAGS = -DUSE_LOCALE_DISTANCE
CFLAGS = $(OPT) $(DEBUG) $(OMP)
LIBS := -limf

all: $(PROGRAM)

$(PROGRAM): $(OBJECTS)
	$(LD) -o $@ $(LDFLAGS) $(OMP) $(OBJECTS) $(LIBS)

$(OBJECTS): common.h

clean:
	$(RM) $(PROGRAM) $(OBJECTS)

# vim:sw=8:sts=8:noexpandtab:
